### PR TITLE
Features & Updates

### PR DESCRIPTION
**Pull request by danielstuart14**
Fixes some things that was getting me crazy.
Also, enable spyglass variable check. But without ending the mission if it doesn't allow the variable. (Look the commit., now we can debug it.)
Add textures for civs & cops. (A flawless & centralized method, without fps drops.)
Update weapon shops config files to new format. (Thx @Itsyuka)
Add custom SQL .ini, updated to latest extdb2 release.
Etc & etc...

Now it's playable, still needing some work after latest tonic commit, but works & works well.

### CODE REVIEW

**Comment by danielstuart14** [comment]
@Itsyuka & @Heavybob I merged to this pull-request some fixes... One of my latest commits fixes the vehicle color. Here: https://github.com/danielstuart14/Altis-Life/commit/d781d6dc007e664763d0bd3c5daf6e8b8b813a7c

Waiting merge.

**Comment by Heavybob** [comment]
Checking your commit, will let you know how it turns out. Thanks for being a good sport.

**Comment by Heavybob** [comment]
Tested the jib solution, flags spyglass.

**Comment by danielstuart14** [comment]
hmm, any log?

**Comment by Heavybob** [comment]
I'm on teamspeak if you are interested in chatting. Give me a sec and I'll drop a log.

**Comment by Itsyuka** [comment]
Bah, reverting everything, I'll do it myself

**Comment by sargken** [comment]
Has there been any benifits from using the updated extdb2?

**Comment by danielstuart14** [comment]
It's fastest and more stable. Also, it's the only one supported now.
We can't found extdb v1 linux binaries anymore.

**Comment by danielstuart14** [comment]
also, this pull-request isn't compatible anymore, will close.

**Pull request closed without merging**
