### PR TITLE
Update remoteexec.txt

### PR DESCRIPTION
**Pull request by Angrygargamel**
wouldnt stop real hackers who know what they are doing but should take out some script kiddies at least

### CODE REVIEW

**Comment by GameTimer** [comment]
Add it into scipts.txt and will do a good job :)

**Comment by chris579** [comment]
Yeah, at least in times where such a troll kid can bypass BE

**Comment by GameTimer** [comment]
Well, we use it in the scripts.txt and it has done its job well - kicked everyone trying to use the toString bypass.

**Comment by chris579** [comment]
Give a shit on that simple bypass, just create a variable with over over 1000 chars and battleye is out

**Pull request closed without merging**
